server:
  port: 8761  # Eureka 서버 포트 설정

spring:
  application:
    name: e-commerce-service  # 서비스 이름 설정

eureka:
  client:
    register-with-eureka: false  # Eureka 서버 자체는 다른 서버에 등록할 필요 없음
    fetch-registry: false  # 다른 서비스 레지스트리를 가져오지 않음